BEGIN TRANSACTION;

INSERT INTO "DataSource" (
  "id",
  "name",
  "sourceType",
  "supportedDataGroups",
  "usageStatus",
  "licenseStatus",
  "tosStatus",
  "accessMethod",
  "cachingAllowed",
  "redistributionAllowed",
  "runtimeDisplayAllowed",
  "derivedDataAllowed",
  "attributionText",
  "notes",
  "createdAt",
  "updatedAt"
) VALUES (
  'sample-demo-source',
  'Atelier Finance sample dataset',
  'curated_internal',
  '["company_profile","financial_statement","market"]',
  'research_only',
  'not_checked',
  'not_checked',
  'manual_fixture',
  'false',
  'false',
  'false',
  'true',
  NULL,
  'Sample/demo seed data for local development only. Not production-approved.',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
)
ON CONFLICT("id") DO UPDATE SET
  "name" = excluded."name",
  "sourceType" = excluded."sourceType",
  "supportedDataGroups" = excluded."supportedDataGroups",
  "usageStatus" = excluded."usageStatus",
  "licenseStatus" = excluded."licenseStatus",
  "tosStatus" = excluded."tosStatus",
  "accessMethod" = excluded."accessMethod",
  "cachingAllowed" = excluded."cachingAllowed",
  "redistributionAllowed" = excluded."redistributionAllowed",
  "runtimeDisplayAllowed" = excluded."runtimeDisplayAllowed",
  "derivedDataAllowed" = excluded."derivedDataAllowed",
  "attributionText" = excluded."attributionText",
  "notes" = excluded."notes",
  "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "SourceEvidence" (
  "id",
  "sourceId",
  "homepageUrl",
  "documentationUrl",
  "licenseName",
  "licenseUrl",
  "termsUrl",
  "allowsPersonalUse",
  "allowsAcademicUse",
  "allowsCommercialUse",
  "allowsRuntimeDisplay",
  "allowsCaching",
  "allowsRedistribution",
  "allowsDerivedData",
  "requiresAttribution",
  "evidenceStatus",
  "reviewedAt",
  "reviewedBy",
  "reviewNote",
  "notes",
  "risks",
  "blockedReason",
  "createdAt",
  "updatedAt"
) VALUES (
  'sample-source-evidence',
  'sample-demo-source',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  'true',
  'true',
  'false',
  'false',
  'false',
  'false',
  'true',
  'false',
  'missing',
  NULL,
  NULL,
  NULL,
  'Seed data evidence marks this source as sample/demo only.',
  '["sample_data","not_production_approved"]',
  'Sample/demo source only.',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
)
ON CONFLICT("id") DO UPDATE SET
  "sourceId" = excluded."sourceId",
  "homepageUrl" = excluded."homepageUrl",
  "documentationUrl" = excluded."documentationUrl",
  "licenseName" = excluded."licenseName",
  "licenseUrl" = excluded."licenseUrl",
  "termsUrl" = excluded."termsUrl",
  "allowsPersonalUse" = excluded."allowsPersonalUse",
  "allowsAcademicUse" = excluded."allowsAcademicUse",
  "allowsCommercialUse" = excluded."allowsCommercialUse",
  "allowsRuntimeDisplay" = excluded."allowsRuntimeDisplay",
  "allowsCaching" = excluded."allowsCaching",
  "allowsRedistribution" = excluded."allowsRedistribution",
  "allowsDerivedData" = excluded."allowsDerivedData",
  "requiresAttribution" = excluded."requiresAttribution",
  "evidenceStatus" = excluded."evidenceStatus",
  "reviewedAt" = excluded."reviewedAt",
  "reviewedBy" = excluded."reviewedBy",
  "reviewNote" = excluded."reviewNote",
  "notes" = excluded."notes",
  "risks" = excluded."risks",
  "blockedReason" = excluded."blockedReason",
  "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Company" (
  "id",
  "ticker",
  "exchange",
  "companyName",
  "companyType",
  "industryCode",
  "industryName",
  "country",
  "currency",
  "dataMode",
  "profileSourceId",
  "profileAsOf",
  "createdAt",
  "updatedAt"
) VALUES (
  'sample-company-fpt-lab',
  'FPTLAB',
  'SAMPLE',
  'FPT Lab Sample Company',
  'non_financial',
  'SAMPLE_TECH',
  'Sample Technology',
  'VN',
  'VND',
  'sample',
  'sample-demo-source',
  '2026-01-31T00:00:00.000Z',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
)
ON CONFLICT("id") DO UPDATE SET
  "ticker" = excluded."ticker",
  "exchange" = excluded."exchange",
  "companyName" = excluded."companyName",
  "companyType" = excluded."companyType",
  "industryCode" = excluded."industryCode",
  "industryName" = excluded."industryName",
  "country" = excluded."country",
  "currency" = excluded."currency",
  "dataMode" = excluded."dataMode",
  "profileSourceId" = excluded."profileSourceId",
  "profileAsOf" = excluded."profileAsOf",
  "updatedAt" = CURRENT_TIMESTAMP;

DELETE FROM "FinancialStatement"
WHERE "companyId" = 'sample-company-fpt-lab'
  AND "sourceId" = 'sample-demo-source';

INSERT INTO "FinancialStatement" (
  "id",
  "companyId",
  "ticker",
  "companyType",
  "periodType",
  "period",
  "fiscalYear",
  "fiscalQuarter",
  "reportDate",
  "publishedDate",
  "currency",
  "unit",
  "revenue",
  "grossProfit",
  "netIncome",
  "operatingCashFlow",
  "totalAssets",
  "equity",
  "totalDebt",
  "currentAssets",
  "currentLiabilities",
  "eps",
  "bvps",
  "sharesOutstanding",
  "marketCap",
  "enterpriseValue",
  "sourceId",
  "sourceLabel",
  "sourceType",
  "dataMode",
  "asOf",
  "collectedAt",
  "qualityStatus",
  "readiness",
  "missingFields",
  "warningCodes",
  "errorCodes",
  "createdAt",
  "updatedAt"
) VALUES
(
  'sample-financial-fptlab-2025q4',
  'sample-company-fpt-lab',
  'FPTLAB',
  'non_financial',
  'quarter',
  '2025Q4',
  2025,
  4,
  '2026-01-31T00:00:00.000Z',
  '2026-02-15T00:00:00.000Z',
  'VND',
  'VND',
  62000000000000,
  24500000000000,
  9300000000000,
  8500000000000,
  72000000000000,
  31000000000000,
  12000000000000,
  28000000000000,
  16000000000000,
  5200,
  21000,
  1000000000,
  NULL,
  NULL,
  'sample-demo-source',
  'Atelier Finance sample dataset',
  'curated_internal',
  'sample',
  '2026-02-15T00:00:00.000Z',
  '2026-02-16T00:00:00.000Z',
  'sample',
  'needs_review',
  '[]',
  '["DEMO_DATA"]',
  '[]',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'sample-financial-fptlab-2025q3',
  'sample-company-fpt-lab',
  'FPTLAB',
  'non_financial',
  'quarter',
  '2025Q3',
  2025,
  3,
  '2025-10-31T00:00:00.000Z',
  '2025-11-15T00:00:00.000Z',
  'VND',
  'VND',
  59000000000000,
  23100000000000,
  8700000000000,
  NULL,
  70000000000000,
  30000000000000,
  11800000000000,
  NULL,
  NULL,
  5000,
  20500,
  1000000000,
  NULL,
  NULL,
  'sample-demo-source',
  'Atelier Finance sample dataset',
  'curated_internal',
  'sample',
  '2025-11-15T00:00:00.000Z',
  '2025-11-16T00:00:00.000Z',
  'sample',
  'needs_review',
  '["operatingCashFlow","currentAssets","currentLiabilities"]',
  '["DEMO_DATA","MISSING_DATA"]',
  '[]',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
);

DELETE FROM "MarketPrice"
WHERE "companyId" = 'sample-company-fpt-lab'
  AND "sourceId" = 'sample-demo-source';

INSERT INTO "MarketPrice" (
  "id",
  "companyId",
  "ticker",
  "tradingDate",
  "periodType",
  "period",
  "openPrice",
  "highPrice",
  "lowPrice",
  "closePrice",
  "previousClose",
  "adjustedClosePrice",
  "volume",
  "tradingValue",
  "marketCap",
  "currency",
  "sourceId",
  "sourceLabel",
  "sourceType",
  "dataMode",
  "asOf",
  "collectedAt",
  "qualityStatus",
  "readiness",
  "missingFields",
  "warningCodes",
  "errorCodes",
  "createdAt",
  "updatedAt"
) VALUES
(
  'sample-market-fptlab-20260216',
  'sample-company-fpt-lab',
  'FPTLAB',
  '2026-02-16T00:00:00.000Z',
  'day',
  '2026-02-16',
  95000,
  97000,
  94000,
  96000,
  95000,
  NULL,
  1200000,
  115200000000,
  NULL,
  'VND',
  'sample-demo-source',
  'Atelier Finance sample dataset',
  'curated_internal',
  'demo',
  '2026-02-16T00:00:00.000Z',
  '2026-02-16T12:00:00.000Z',
  'demo',
  'needs_review',
  '["adjustedClosePrice","marketCap"]',
  '["DEMO_DATA"]',
  '[]',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'sample-market-fptlab-20260213',
  'sample-company-fpt-lab',
  'FPTLAB',
  '2026-02-13T00:00:00.000Z',
  'day',
  '2026-02-13',
  94000,
  95500,
  93000,
  95000,
  94000,
  NULL,
  980000,
  93100000000,
  NULL,
  'VND',
  'sample-demo-source',
  'Atelier Finance sample dataset',
  'curated_internal',
  'demo',
  '2026-02-13T00:00:00.000Z',
  '2026-02-13T12:00:00.000Z',
  'demo',
  'needs_review',
  '["adjustedClosePrice","marketCap"]',
  '["DEMO_DATA"]',
  '[]',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
);

INSERT INTO "DataQualityReport" (
  "id",
  "scopeType",
  "scopeId",
  "status",
  "readiness",
  "qualityStatus",
  "missingFields",
  "warningCodes",
  "errorCodes",
  "topIssues",
  "fieldCoverage",
  "safeNextSteps",
  "generatedAt",
  "calculationVersion"
) VALUES (
  'sample-quality-report-fpt-lab',
  'local_seed',
  'sample-company-fpt-lab',
  'needs_review',
  'needs_review',
  'sample',
  '["adjustedClosePrice","marketCap"]',
  '["DEMO_DATA","SOURCE_NOT_PRODUCTION_APPROVED"]',
  '[]',
  '[{"code":"DEMO_DATA","message":"Local seed data is sample/demo only."}]',
  '[]',
  '["Use only for local API smoke tests."]',
  CURRENT_TIMESTAMP,
  'phase-29e-seed-v1'
)
ON CONFLICT("id") DO UPDATE SET
  "scopeType" = excluded."scopeType",
  "scopeId" = excluded."scopeId",
  "status" = excluded."status",
  "readiness" = excluded."readiness",
  "qualityStatus" = excluded."qualityStatus",
  "missingFields" = excluded."missingFields",
  "warningCodes" = excluded."warningCodes",
  "errorCodes" = excluded."errorCodes",
  "topIssues" = excluded."topIssues",
  "fieldCoverage" = excluded."fieldCoverage",
  "safeNextSteps" = excluded."safeNextSteps",
  "generatedAt" = CURRENT_TIMESTAMP,
  "calculationVersion" = excluded."calculationVersion";

COMMIT;
