import { MacroObservationFrequency } from "./macro-stale-policy";

export type MacroIndicatorSupportStatus =
  | "db_backed"
  | "candidate_source_identified"
  | "source_assessment_needed"
  | "planned"
  | "unsupported";

export type MacroIndicatorRegistryItem = {
  indicatorCode: string;
  displayName: string;
  category: "growth" | "inflation" | "rates" | "fx" | "market";
  description: string;
  expectedUnit?: string;
  expectedFrequency?: MacroObservationFrequency;
  regionScope: "VN" | "US" | "GLOBAL" | "MIXED";
  supportStatus: MacroIndicatorSupportStatus;
  sourceCandidate?: string;
  sourceLabel?: string;
  dbBacked?: boolean;
  productionApproved: false;
  needsReview: true;
  limitations: string[];
  
  // Phase 148B Frontend Locking Fields
  inCurrentFrontend: boolean;
  frontendDisplayOrder?: number;
  frontendSection?: string;
  providerExpansionEligible: boolean;
};

export const MACRO_INDICATOR_UNIVERSE: MacroIndicatorRegistryItem[] = [
  // --- Tăng trưởng kinh tế (Growth) ---
  {
    indicatorCode: "GDP_GROWTH",
    displayName: "Tăng trưởng GDP",
    category: "growth",
    description: "Tăng trưởng tổng sản phẩm quốc nội so với cùng kỳ.",
    expectedUnit: "% YoY",
    expectedFrequency: "annual",
    regionScope: "VN",
    supportStatus: "db_backed",
    sourceCandidate: "World Bank API",
    sourceLabel: "world_bank_candidate",
    dbBacked: true,
    productionApproved: false,
    needsReview: true,
    limitations: ["Dữ liệu từ nguồn public candidate, có thể thiếu cập nhật nhanh."],
    inCurrentFrontend: true,
    frontendDisplayOrder: 1,
    frontendSection: "vietnamMetrics",
    providerExpansionEligible: false, // already db_backed
  },
  {
    indicatorCode: "INDUSTRIAL_PRODUCTION_GROWTH",
    displayName: "Chỉ số sản xuất công nghiệp (IIP)",
    category: "growth",
    description: "Phản ánh mức độ tăng trưởng sản xuất của các ngành công nghiệp.",
    expectedUnit: "% YoY",
    expectedFrequency: "monthly",
    regionScope: "VN",
    supportStatus: "candidate_source_identified",
    sourceCandidate: "GSO",
    dbBacked: false,
    productionApproved: false,
    needsReview: true,
    limitations: [],
    inCurrentFrontend: false,
    providerExpansionEligible: false,
  },
  {
    indicatorCode: "RETAIL_SALES_GROWTH",
    displayName: "Bán lẻ hàng hóa & Dịch vụ",
    category: "growth",
    description: "Tổng mức bán lẻ hàng hóa và doanh thu dịch vụ tiêu dùng.",
    expectedUnit: "% YoY",
    expectedFrequency: "monthly",
    regionScope: "VN",
    supportStatus: "candidate_source_identified",
    sourceCandidate: "GSO",
    dbBacked: false,
    productionApproved: false,
    needsReview: true,
    limitations: [],
    inCurrentFrontend: false,
    providerExpansionEligible: false,
  },
  {
    indicatorCode: "PMI_MANUFACTURING",
    displayName: "Chỉ số PMI",
    category: "growth",
    description: "Chỉ số quản trị mua hàng ngành công nghiệp chế biến, chế tạo.",
    expectedUnit: "Points",
    expectedFrequency: "monthly",
    regionScope: "VN",
    supportStatus: "source_assessment_needed",
    dbBacked: false,
    productionApproved: false,
    needsReview: true,
    limitations: ["Cần kiểm tra bản quyền dữ liệu của S&P Global PMI."],
    inCurrentFrontend: true,
    frontendDisplayOrder: 2,
    frontendSection: "vietnamMetrics",
    providerExpansionEligible: true,
  },
  {
    indicatorCode: "FDI_REGISTERED",
    displayName: "FDI Đăng ký",
    category: "growth",
    description: "Tổng vốn đầu tư trực tiếp nước ngoài đăng ký vào VN.",
    expectedUnit: "Billion USD",
    expectedFrequency: "monthly",
    regionScope: "VN",
    supportStatus: "candidate_source_identified",
    sourceCandidate: "GSO",
    dbBacked: false,
    productionApproved: false,
    needsReview: true,
    limitations: [],
    inCurrentFrontend: false,
    providerExpansionEligible: false,
  },
  {
    indicatorCode: "FDI_DISBURSED",
    displayName: "FDI Giải ngân",
    category: "growth",
    description: "Tổng vốn đầu tư trực tiếp nước ngoài thực hiện tại VN.",
    expectedUnit: "Billion USD",
    expectedFrequency: "monthly",
    regionScope: "VN",
    supportStatus: "candidate_source_identified",
    sourceCandidate: "GSO",
    dbBacked: false,
    productionApproved: false,
    needsReview: true,
    limitations: [],
    inCurrentFrontend: false,
    providerExpansionEligible: false,
  },
  {
    indicatorCode: "EXPORT_GROWTH",
    displayName: "Xuất khẩu",
    category: "growth",
    description: "Tăng trưởng kim ngạch xuất khẩu.",
    expectedUnit: "% YoY",
    expectedFrequency: "monthly",
    regionScope: "VN",
    supportStatus: "candidate_source_identified",
    sourceCandidate: "GSO",
    dbBacked: false,
    productionApproved: false,
    needsReview: true,
    limitations: [],
    inCurrentFrontend: true,
    frontendDisplayOrder: 3,
    frontendSection: "vietnamMetrics",
    providerExpansionEligible: true,
  },
  {
    indicatorCode: "IMPORT_GROWTH",
    displayName: "Nhập khẩu",
    category: "growth",
    description: "Tăng trưởng kim ngạch nhập khẩu.",
    expectedUnit: "% YoY",
    expectedFrequency: "monthly",
    regionScope: "VN",
    supportStatus: "candidate_source_identified",
    sourceCandidate: "GSO",
    dbBacked: false,
    productionApproved: false,
    needsReview: true,
    limitations: [],
    inCurrentFrontend: false,
    providerExpansionEligible: false,
  },
  {
    indicatorCode: "TRADE_BALANCE",
    displayName: "Cán cân thương mại",
    category: "growth",
    description: "Chênh lệch xuất nhập khẩu.",
    expectedUnit: "Billion USD",
    expectedFrequency: "monthly",
    regionScope: "VN",
    supportStatus: "candidate_source_identified",
    sourceCandidate: "GSO",
    dbBacked: false,
    productionApproved: false,
    needsReview: true,
    limitations: [],
    inCurrentFrontend: false,
    providerExpansionEligible: false,
  },
  {
    indicatorCode: "PUBLIC_INVESTMENT",
    displayName: "Đầu tư công",
    category: "growth",
    description: "Vốn đầu tư công thực hiện.",
    expectedUnit: "% YoY",
    expectedFrequency: "monthly",
    regionScope: "VN",
    supportStatus: "source_assessment_needed",
    dbBacked: false,
    productionApproved: false,
    needsReview: true,
    limitations: [],
    inCurrentFrontend: true,
    providerExpansionEligible: true,
  },

  // --- Lạm phát (Inflation) ---
  {
    indicatorCode: "CPI_YOY",
    displayName: "Chỉ số giá tiêu dùng (CPI YoY)",
    category: "inflation",
    description: "Lạm phát so với cùng kỳ năm trước.",
    expectedUnit: "% YoY",
    expectedFrequency: "annual",
    regionScope: "VN",
    supportStatus: "db_backed",
    sourceCandidate: "World Bank API",
    sourceLabel: "world_bank_candidate",
    dbBacked: true,
    productionApproved: false,
    needsReview: true,
    limitations: ["World Bank API chỉ cung cấp theo năm, cần nguồn hàng tháng để kịp thời hơn."],
    inCurrentFrontend: true,
    frontendDisplayOrder: 1,
    frontendSection: "vietnamMetrics",
    providerExpansionEligible: false, // already db_backed
  },
  {
    indicatorCode: "CPI_MOM",
    displayName: "CPI MoM",
    category: "inflation",
    description: "Lạm phát so với tháng trước.",
    expectedUnit: "% MoM",
    expectedFrequency: "monthly",
    regionScope: "VN",
    supportStatus: "candidate_source_identified",
    sourceCandidate: "GSO",
    dbBacked: false,
    productionApproved: false,
    needsReview: true,
    limitations: [],
    inCurrentFrontend: false,
    providerExpansionEligible: false,
  },
  {
    indicatorCode: "CORE_INFLATION",
    displayName: "Lạm phát cơ bản",
    category: "inflation",
    description: "Lạm phát loại trừ các mặt hàng biến động như thực phẩm, năng lượng.",
    expectedUnit: "% YoY",
    expectedFrequency: "monthly",
    regionScope: "VN",
    supportStatus: "candidate_source_identified",
    sourceCandidate: "GSO",
    dbBacked: false,
    productionApproved: false,
    needsReview: true,
    limitations: [],
    inCurrentFrontend: false,
    providerExpansionEligible: false,
  },
  {
    indicatorCode: "PPI",
    displayName: "Chỉ số giá sản xuất (PPI)",
    category: "inflation",
    description: "Biến động giá ở khâu sản xuất.",
    expectedUnit: "% YoY",
    expectedFrequency: "monthly",
    regionScope: "VN",
    supportStatus: "source_assessment_needed",
    dbBacked: false,
    productionApproved: false,
    needsReview: true,
    limitations: [],
    inCurrentFrontend: false,
    providerExpansionEligible: false,
  },
  {
    indicatorCode: "BRENT_OIL_PRICE",
    displayName: "Giá dầu Brent",
    category: "inflation",
    description: "Đại diện chi phí năng lượng toàn cầu.",
    expectedUnit: "USD/Barrel",
    expectedFrequency: "daily",
    regionScope: "GLOBAL",
    supportStatus: "source_assessment_needed",
    dbBacked: false,
    productionApproved: false,
    needsReview: true,
    limitations: ["Cần nguồn open data daily tin cậy."],
    inCurrentFrontend: true,
    frontendSection: "worldMetrics",
    providerExpansionEligible: true,
  },

  // --- Lãi suất và Tiền tệ (Rates & Monetary) ---
  {
    indicatorCode: "POLICY_RATE",
    displayName: "Lãi suất điều hành",
    category: "rates",
    description: "Lãi suất tái cấp vốn / chiết khấu từ NHNN.",
    expectedUnit: "%",
    expectedFrequency: "event_based",
    regionScope: "VN",
    supportStatus: "candidate_source_identified",
    sourceCandidate: "SBV",
    dbBacked: false,
    productionApproved: false,
    needsReview: true,
    limitations: ["Nguồn SBV thường HTML parsing, thiếu API."],
    inCurrentFrontend: true,
    frontendSection: "vietnamMetrics",
    providerExpansionEligible: true,
  },
  {
    indicatorCode: "INTERBANK_RATE_OVERNIGHT",
    displayName: "Lãi suất liên ngân hàng (O/N)",
    category: "rates",
    description: "Phản ánh thanh khoản hệ thống ngân hàng ngắn hạn.",
    expectedUnit: "%",
    expectedFrequency: "daily",
    regionScope: "VN",
    supportStatus: "candidate_source_identified",
    sourceCandidate: "SBV",
    dbBacked: false,
    productionApproved: false,
    needsReview: true,
    limitations: ["Cần HTML scraping trên SBV."],
    inCurrentFrontend: false,
    providerExpansionEligible: false,
  },
  {
    indicatorCode: "CREDIT_GROWTH",
    displayName: "Tăng trưởng tín dụng",
    category: "rates",
    description: "Mức độ mở rộng tín dụng của hệ thống ngân hàng.",
    expectedUnit: "% YTD",
    expectedFrequency: "monthly",
    regionScope: "VN",
    supportStatus: "source_assessment_needed",
    dbBacked: false,
    productionApproved: false,
    needsReview: true,
    limitations: ["SBV công bố không đều đặn."],
    inCurrentFrontend: true,
    frontendSection: "vietnamMetrics",
    providerExpansionEligible: true,
  },
  {
    indicatorCode: "M2_GROWTH",
    displayName: "Cung tiền M2",
    category: "rates",
    description: "Tăng trưởng tổng phương tiện thanh toán.",
    expectedUnit: "% YoY",
    expectedFrequency: "monthly",
    regionScope: "VN",
    supportStatus: "source_assessment_needed",
    dbBacked: false,
    productionApproved: false,
    needsReview: true,
    limitations: ["Độ trễ công bố rất lớn (2-3 tháng)."],
    inCurrentFrontend: false,
    providerExpansionEligible: false,
  },
  {
    indicatorCode: "GOV_BOND_YIELD_10Y",
    displayName: "Lợi suất TPCP 10 năm VN",
    category: "rates",
    description: "Chi phí vốn dài hạn không rủi ro.",
    expectedUnit: "%",
    expectedFrequency: "daily",
    regionScope: "VN",
    supportStatus: "source_assessment_needed",
    dbBacked: false,
    productionApproved: false,
    needsReview: true,
    limitations: ["Nguồn dữ liệu HNX thường khó trích xuất tự động."],
    inCurrentFrontend: false,
    providerExpansionEligible: false,
  },

  // --- Tỷ giá và Quốc tế (FX & Global) ---
  {
    indicatorCode: "USD_VND",
    displayName: "Tỷ giá trung tâm USD/VND",
    category: "fx",
    description: "Tỷ giá tham chiếu do NHNN công bố.",
    expectedUnit: "VND",
    expectedFrequency: "daily",
    regionScope: "VN",
    supportStatus: "candidate_source_identified",
    sourceCandidate: "SBV",
    dbBacked: false,
    productionApproved: false,
    needsReview: true,
    limitations: ["HTML Scraping"],
    inCurrentFrontend: true,
    frontendSection: "vietnamMetrics",
    providerExpansionEligible: true,
  },
  {
    indicatorCode: "DXY",
    displayName: "Chỉ số USD (DXY)",
    category: "fx",
    description: "Sức mạnh đồng USD so với rổ tiền tệ lớn.",
    expectedUnit: "Points",
    expectedFrequency: "daily",
    regionScope: "GLOBAL",
    supportStatus: "source_assessment_needed",
    dbBacked: false,
    productionApproved: false,
    needsReview: true,
    limitations: [],
    inCurrentFrontend: true,
    frontendSection: "worldMetrics",
    providerExpansionEligible: true,
  },
  {
    indicatorCode: "FED_FUNDS_RATE",
    displayName: "Lãi suất Fed",
    category: "rates",
    description: "Lãi suất điều hành của Mỹ, ảnh hưởng vĩ mô toàn cầu.",
    expectedUnit: "%",
    expectedFrequency: "event_based",
    regionScope: "US",
    supportStatus: "candidate_source_identified",
    sourceCandidate: "FRED",
    dbBacked: false,
    productionApproved: false,
    needsReview: true,
    limitations: [],
    inCurrentFrontend: true,
    frontendSection: "worldMetrics",
    providerExpansionEligible: true,
  },
  {
    indicatorCode: "US_10Y_YIELD",
    displayName: "Lợi suất TPCP Mỹ 10 năm",
    category: "rates",
    description: "Định vị rủi ro và kỳ vọng lạm phát toàn cầu.",
    expectedUnit: "%",
    expectedFrequency: "daily",
    regionScope: "US",
    supportStatus: "candidate_source_identified",
    sourceCandidate: "FRED",
    dbBacked: false,
    productionApproved: false,
    needsReview: true,
    limitations: [],
    inCurrentFrontend: false,
    providerExpansionEligible: false,
  },
  {
    indicatorCode: "GLOBAL_FLOW",
    displayName: "Dòng vốn toàn cầu",
    category: "market",
    description: "Dòng dịch chuyển vốn trên thế giới.",
    expectedUnit: "Unknown",
    expectedFrequency: "unknown",
    regionScope: "GLOBAL",
    supportStatus: "source_assessment_needed",
    dbBacked: false,
    productionApproved: false,
    needsReview: true,
    limitations: [],
    inCurrentFrontend: true,
    frontendSection: "worldMetrics",
    providerExpansionEligible: true,
  },

  // --- Thị trường chứng khoán (Market) ---
  {
    indicatorCode: "VNINDEX_CLOSE",
    displayName: "Chỉ số VN-Index",
    category: "market",
    description: "Đại diện tổng quát thị trường chứng khoán VN.",
    expectedUnit: "Points",
    expectedFrequency: "daily",
    regionScope: "VN",
    supportStatus: "planned",
    dbBacked: false,
    productionApproved: false,
    needsReview: true,
    limitations: ["Nên sử dụng nguồn MarketPrice hiện tại để tính toán hoặc fetch từ Vnstock."],
    inCurrentFrontend: false,
    providerExpansionEligible: false,
  },
  {
    indicatorCode: "VN30_CLOSE",
    displayName: "Chỉ số VN30",
    category: "market",
    description: "30 cổ phiếu vốn hóa lớn nhất.",
    expectedUnit: "Points",
    expectedFrequency: "daily",
    regionScope: "VN",
    supportStatus: "planned",
    dbBacked: false,
    productionApproved: false,
    needsReview: true,
    limitations: [],
    inCurrentFrontend: false,
    providerExpansionEligible: false,
  },
  {
    indicatorCode: "MARKET_TRADING_VALUE",
    displayName: "Thanh khoản thị trường",
    category: "market",
    description: "Tổng giá trị giao dịch khớp lệnh.",
    expectedUnit: "Billion VND",
    expectedFrequency: "daily",
    regionScope: "VN",
    supportStatus: "planned",
    dbBacked: false,
    productionApproved: false,
    needsReview: true,
    limitations: [],
    inCurrentFrontend: true,
    frontendSection: "vietnamMetrics",
    providerExpansionEligible: true, // "planned" implies we can assess a source
  },
  {
    indicatorCode: "FOREIGN_NET_FLOW",
    displayName: "Giao dịch Khối ngoại",
    category: "market",
    description: "Giá trị mua bán ròng của nhà đầu tư nước ngoài.",
    expectedUnit: "Billion VND",
    expectedFrequency: "daily",
    regionScope: "VN",
    supportStatus: "planned",
    dbBacked: false,
    productionApproved: false,
    needsReview: true,
    limitations: [],
    inCurrentFrontend: true,
    frontendSection: "vietnamMetrics",
    providerExpansionEligible: true, // "planned" can be eligible
  }
];
