export type MacroIndicatorSupportStatus =
  | "db_backed"
  | "candidate_source_identified"
  | "source_assessment_needed"
  | "planned"
  | "unsupported";

export type MacroIndicatorRegistryItem = {
  indicatorCode: string;
  displayName: string;
  category: "growth" | "inflation" | "rates" | "fx" | "market";
  description: string;
  expectedUnit?: string;
  expectedFrequency?: "daily" | "monthly" | "quarterly" | "annual" | "mixed" | "unknown";
  regionScope: "VN" | "US" | "GLOBAL" | "MIXED";
  supportStatus: MacroIndicatorSupportStatus;
  sourceCandidate?: string;
  sourceLabel?: string;
  dbBacked?: boolean;
  productionApproved: false;
  needsReview: true;
  limitations: string[];
};

export const MACRO_INDICATOR_UNIVERSE: MacroIndicatorRegistryItem[] = [
  // --- Tăng trưởng kinh tế (Growth) ---
  {
    indicatorCode: "GDP_GROWTH",
    displayName: "Tăng trưởng GDP",
    category: "growth",
    description: "Tăng trưởng tổng sản phẩm quốc nội so với cùng kỳ.",
    expectedUnit: "% YoY",
    expectedFrequency: "annual", // Currently fetching annual from World Bank
    regionScope: "VN",
    supportStatus: "db_backed",
    sourceCandidate: "World Bank API",
    sourceLabel: "world_bank_candidate",
    dbBacked: true,
    productionApproved: false,
    needsReview: true,
    limitations: ["Dữ liệu từ nguồn public candidate, có thể thiếu cập nhật nhanh."],
  },
  {
    indicatorCode: "INDUSTRIAL_PRODUCTION_GROWTH",
    displayName: "Chỉ số sản xuất công nghiệp (IIP)",
    category: "growth",
    description: "Phản ánh mức độ tăng trưởng sản xuất của các ngành công nghiệp.",
    expectedUnit: "% YoY",
    expectedFrequency: "monthly",
    regionScope: "VN",
    supportStatus: "candidate_source_identified",
    sourceCandidate: "GSO",
    dbBacked: false,
    productionApproved: false,
    needsReview: true,
    limitations: [],
  },
  {
    indicatorCode: "RETAIL_SALES_GROWTH",
    displayName: "Bán lẻ hàng hóa & Dịch vụ",
    category: "growth",
    description: "Tổng mức bán lẻ hàng hóa và doanh thu dịch vụ tiêu dùng.",
    expectedUnit: "% YoY",
    expectedFrequency: "monthly",
    regionScope: "VN",
    supportStatus: "candidate_source_identified",
    sourceCandidate: "GSO",
    dbBacked: false,
    productionApproved: false,
    needsReview: true,
    limitations: [],
  },
  {
    indicatorCode: "PMI_MANUFACTURING",
    displayName: "Chỉ số PMI",
    category: "growth",
    description: "Chỉ số quản trị mua hàng ngành công nghiệp chế biến, chế tạo.",
    expectedUnit: "Points",
    expectedFrequency: "monthly",
    regionScope: "VN",
    supportStatus: "source_assessment_needed",
    dbBacked: false,
    productionApproved: false,
    needsReview: true,
    limitations: ["Cần kiểm tra bản quyền dữ liệu của S&P Global PMI."],
  },
  {
    indicatorCode: "FDI_REGISTERED",
    displayName: "FDI Đăng ký",
    category: "growth",
    description: "Tổng vốn đầu tư trực tiếp nước ngoài đăng ký vào VN.",
    expectedUnit: "Billion USD",
    expectedFrequency: "monthly",
    regionScope: "VN",
    supportStatus: "candidate_source_identified",
    sourceCandidate: "GSO",
    dbBacked: false,
    productionApproved: false,
    needsReview: true,
    limitations: [],
  },
  {
    indicatorCode: "FDI_DISBURSED",
    displayName: "FDI Giải ngân",
    category: "growth",
    description: "Vốn đầu tư trực tiếp nước ngoài thực hiện.",
    expectedUnit: "Billion USD",
    expectedFrequency: "monthly",
    regionScope: "VN",
    supportStatus: "candidate_source_identified",
    sourceCandidate: "GSO",
    dbBacked: false,
    productionApproved: false,
    needsReview: true,
    limitations: [],
  },
  {
    indicatorCode: "EXPORT_GROWTH",
    displayName: "Tăng trưởng xuất khẩu",
    category: "growth",
    description: "Tốc độ tăng/giảm kim ngạch xuất khẩu hàng hóa.",
    expectedUnit: "% YoY",
    expectedFrequency: "monthly",
    regionScope: "VN",
    supportStatus: "candidate_source_identified",
    sourceCandidate: "GSO",
    dbBacked: false,
    productionApproved: false,
    needsReview: true,
    limitations: [],
  },
  {
    indicatorCode: "IMPORT_GROWTH",
    displayName: "Tăng trưởng nhập khẩu",
    category: "growth",
    description: "Tốc độ tăng/giảm kim ngạch nhập khẩu hàng hóa.",
    expectedUnit: "% YoY",
    expectedFrequency: "monthly",
    regionScope: "VN",
    supportStatus: "candidate_source_identified",
    sourceCandidate: "GSO",
    dbBacked: false,
    productionApproved: false,
    needsReview: true,
    limitations: [],
  },
  {
    indicatorCode: "TRADE_BALANCE",
    displayName: "Cán cân thương mại",
    category: "growth",
    description: "Chênh lệch giữa xuất khẩu và nhập khẩu.",
    expectedUnit: "Billion USD",
    expectedFrequency: "monthly",
    regionScope: "VN",
    supportStatus: "candidate_source_identified",
    sourceCandidate: "GSO",
    dbBacked: false,
    productionApproved: false,
    needsReview: true,
    limitations: [],
  },

  // --- Lạm phát và giá cả (Inflation) ---
  {
    indicatorCode: "CPI_YOY",
    displayName: "Lạm phát (CPI)",
    category: "inflation",
    description: "Chỉ số giá tiêu dùng so với cùng kỳ năm trước.",
    expectedUnit: "% YoY",
    expectedFrequency: "annual",
    regionScope: "VN",
    supportStatus: "db_backed",
    sourceCandidate: "World Bank API",
    sourceLabel: "world_bank_candidate",
    dbBacked: true,
    productionApproved: false,
    needsReview: true,
    limitations: ["Dữ liệu từ nguồn public candidate, có thể thiếu cập nhật nhanh."],
  },
  {
    indicatorCode: "CPI_MOM",
    displayName: "Lạm phát (CPI) MoM",
    category: "inflation",
    description: "Chỉ số giá tiêu dùng so với tháng trước.",
    expectedUnit: "% MoM",
    expectedFrequency: "monthly",
    regionScope: "VN",
    supportStatus: "candidate_source_identified",
    sourceCandidate: "GSO",
    dbBacked: false,
    productionApproved: false,
    needsReview: true,
    limitations: [],
  },
  {
    indicatorCode: "CORE_INFLATION",
    displayName: "Lạm phát cơ bản",
    category: "inflation",
    description: "Lạm phát loại trừ các mặt hàng dễ biến động giá.",
    expectedUnit: "% YoY",
    expectedFrequency: "monthly",
    regionScope: "VN",
    supportStatus: "candidate_source_identified",
    sourceCandidate: "GSO",
    dbBacked: false,
    productionApproved: false,
    needsReview: true,
    limitations: [],
  },
  {
    indicatorCode: "PPI",
    displayName: "Chỉ số giá sản xuất (PPI)",
    category: "inflation",
    description: "Chỉ số đo lường mức thay đổi giá bán buôn của các nhà sản xuất.",
    expectedUnit: "% YoY",
    expectedFrequency: "quarterly",
    regionScope: "VN",
    supportStatus: "source_assessment_needed",
    dbBacked: false,
    productionApproved: false,
    needsReview: true,
    limitations: [],
  },
  {
    indicatorCode: "BRENT_OIL_PRICE",
    displayName: "Giá dầu Brent",
    category: "inflation",
    description: "Giá dầu thô Brent thế giới.",
    expectedUnit: "USD/barrel",
    expectedFrequency: "daily",
    regionScope: "GLOBAL",
    supportStatus: "source_assessment_needed",
    dbBacked: false,
    productionApproved: false,
    needsReview: true,
    limitations: ["Cần tìm nguồn API hợp lệ cho dữ liệu lịch sử giá dầu."],
  },

  // --- Lãi suất và tiền tệ (Rates) ---
  {
    indicatorCode: "POLICY_RATE",
    displayName: "Lãi suất điều hành",
    category: "rates",
    description: "Lãi suất tái cấp vốn / tái chiết khấu do NHNN công bố.",
    expectedUnit: "%",
    expectedFrequency: "mixed",
    regionScope: "VN",
    supportStatus: "candidate_source_identified",
    sourceCandidate: "SBV",
    dbBacked: false,
    productionApproved: false,
    needsReview: true,
    limitations: [],
  },
  {
    indicatorCode: "INTERBANK_RATE_OVERNIGHT",
    displayName: "Lãi suất liên ngân hàng qua đêm",
    category: "rates",
    description: "Lãi suất giao dịch VNĐ bình quân trên thị trường liên ngân hàng.",
    expectedUnit: "%",
    expectedFrequency: "daily",
    regionScope: "VN",
    supportStatus: "candidate_source_identified",
    sourceCandidate: "SBV",
    dbBacked: false,
    productionApproved: false,
    needsReview: true,
    limitations: [],
  },
  {
    indicatorCode: "CREDIT_GROWTH",
    displayName: "Tăng trưởng tín dụng",
    category: "rates",
    description: "Tốc độ tăng trưởng dư nợ tín dụng toàn nền kinh tế.",
    expectedUnit: "% YTD",
    expectedFrequency: "mixed",
    regionScope: "VN",
    supportStatus: "source_assessment_needed",
    dbBacked: false,
    productionApproved: false,
    needsReview: true,
    limitations: ["SBV công bố không định kỳ, cần đánh giá cách thu thập."],
  },
  {
    indicatorCode: "M2_GROWTH",
    displayName: "Tăng trưởng cung tiền M2",
    category: "rates",
    description: "Tốc độ tăng trưởng phương tiện thanh toán tổng phương tiện.",
    expectedUnit: "% YTD",
    expectedFrequency: "monthly",
    regionScope: "VN",
    supportStatus: "candidate_source_identified",
    sourceCandidate: "SBV",
    dbBacked: false,
    productionApproved: false,
    needsReview: true,
    limitations: [],
  },
  {
    indicatorCode: "GOV_BOND_YIELD_10Y",
    displayName: "Lợi suất TPCP 10 năm",
    category: "rates",
    description: "Lợi suất trái phiếu chính phủ Việt Nam kỳ hạn 10 năm.",
    expectedUnit: "%",
    expectedFrequency: "daily",
    regionScope: "VN",
    supportStatus: "source_assessment_needed",
    dbBacked: false,
    productionApproved: false,
    needsReview: true,
    limitations: [],
  },

  // --- Tỷ giá và quốc tế (FX) ---
  {
    indicatorCode: "USD_VND",
    displayName: "Tỷ giá USD/VND",
    category: "fx",
    description: "Tỷ giá trung tâm hoặc tỷ giá liên ngân hàng USD/VND.",
    expectedUnit: "VND",
    expectedFrequency: "daily",
    regionScope: "VN",
    supportStatus: "candidate_source_identified",
    sourceCandidate: "SBV",
    dbBacked: false,
    productionApproved: false,
    needsReview: true,
    limitations: [],
  },
  {
    indicatorCode: "DXY",
    displayName: "Chỉ số DXY",
    category: "fx",
    description: "Chỉ số sức mạnh đồng đô la Mỹ.",
    expectedUnit: "Points",
    expectedFrequency: "daily",
    regionScope: "GLOBAL",
    supportStatus: "source_assessment_needed",
    dbBacked: false,
    productionApproved: false,
    needsReview: true,
    limitations: [],
  },
  {
    indicatorCode: "FED_FUNDS_RATE",
    displayName: "Lãi suất Fed (Fed Funds Rate)",
    category: "fx",
    description: "Lãi suất mục tiêu của Cục Dự trữ Liên bang Mỹ.",
    expectedUnit: "%",
    expectedFrequency: "mixed",
    regionScope: "US",
    supportStatus: "candidate_source_identified",
    sourceCandidate: "FRED",
    dbBacked: false,
    productionApproved: false,
    needsReview: true,
    limitations: [],
  },
  {
    indicatorCode: "US_10Y_YIELD",
    displayName: "Lợi suất TP Mỹ 10 năm",
    category: "fx",
    description: "Lợi suất trái phiếu chính phủ Mỹ kỳ hạn 10 năm.",
    expectedUnit: "%",
    expectedFrequency: "daily",
    regionScope: "US",
    supportStatus: "candidate_source_identified",
    sourceCandidate: "FRED",
    dbBacked: false,
    productionApproved: false,
    needsReview: true,
    limitations: [],
  },

  // --- Thị trường chứng khoán và thanh khoản (Market) ---
  {
    indicatorCode: "VNINDEX_CLOSE",
    displayName: "Chỉ số VN-Index",
    category: "market",
    description: "Điểm đóng cửa của VN-Index.",
    expectedUnit: "Points",
    expectedFrequency: "daily",
    regionScope: "VN",
    supportStatus: "candidate_source_identified",
    sourceCandidate: "Market Data Provider",
    dbBacked: false,
    productionApproved: false,
    needsReview: true,
    limitations: [],
  },
  {
    indicatorCode: "VN30_CLOSE",
    displayName: "Chỉ số VN30",
    category: "market",
    description: "Điểm đóng cửa của VN30.",
    expectedUnit: "Points",
    expectedFrequency: "daily",
    regionScope: "VN",
    supportStatus: "candidate_source_identified",
    sourceCandidate: "Market Data Provider",
    dbBacked: false,
    productionApproved: false,
    needsReview: true,
    limitations: [],
  },
  {
    indicatorCode: "MARKET_TRADING_VALUE",
    displayName: "Thanh khoản thị trường",
    category: "market",
    description: "Tổng giá trị giao dịch khớp lệnh trên thị trường.",
    expectedUnit: "Billion VND",
    expectedFrequency: "daily",
    regionScope: "VN",
    supportStatus: "candidate_source_identified",
    sourceCandidate: "Market Data Provider",
    dbBacked: false,
    productionApproved: false,
    needsReview: true,
    limitations: [],
  },
  {
    indicatorCode: "FOREIGN_NET_FLOW",
    displayName: "Giao dịch khối ngoại",
    category: "market",
    description: "Giá trị mua/bán ròng của nhà đầu tư nước ngoài.",
    expectedUnit: "Billion VND",
    expectedFrequency: "daily",
    regionScope: "VN",
    supportStatus: "candidate_source_identified",
    sourceCandidate: "Market Data Provider",
    dbBacked: false,
    productionApproved: false,
    needsReview: true,
    limitations: [],
  },
];
